#!/usr/bin/env bash
PGDIR=$HOME/pg

# --option sanity
if [ ! -z "$1" -a "$1" != "--regress" -a "$1" != "--clean" ]; then
	echo "** invalid option **"
	return 1
fi

# make check?
if [ ! -z "$1" -a "$1" = "--regress" ]; then
	make check
	return 0
fi

# make clean?
if [ ! -z "$1" -a "$1" = "--clean" ]; then
	make clean 2>&1 > /dev/null
	echo "** all cleaned up **"
	echo ""
fi

{
    CFLAGS="-O0 -ggdb -fno-omit-frame-pointer -Wunused -Wreturn-type -Wall" \
    ./configure --enable-debug --enable-cassert --prefix=$PGDIR/install/head
    make -j3 2>&1 | grep -A2 -B2 "warning:"
    make install
} 2>&1 | grep -B1 "warning:\|error:"

# add to PATH only if not already done
currentpgpath=`which postgres`
newpgpath=$PGDIR/install/head/bin/postgres
if [ "$currentpgpath" == "$newpgpath" ]; then
	PATH=$PATH
else
	PATH=$PGDIR/install/head/bin:$PATH
fi
export PATH
return 0
