#!/usr/bin/env bash
PGDIR=$HOME/pg

if [ ! -z "$1" -a "$1" = "--clean" ]; then
	make clean 2>&1 > /dev/null
	echo "all cleaned up"
	echo ""
fi

{
    CFLAGS="-O0 -ggdb -fno-omit-frame-pointer -Wunused -Wreturn-type -Wall" \
    ./configure --enable-debug --enable-cassert --prefix=$PGDIR/install/head
    make -j3 2>&1 | grep -A2 -B2 "warning:"
    make install
} 2>&1 | grep -B1 "warning:\|error:"

export PATH=$PGDIR/install/head/bin:$PATH
export PGDATA=$PGDIR/data/head
