#!/bin/sh
# source: https://www.postgresql.org/message-id/24328.1130449464@sss.pgh.pa.us
# Usage: gdblive [ arguments to grep output of ps ]

PGINSTROOT=$HOME/pg/install/$1
cd $HOME

# tee /dev/tty is for user to see the set of procs considered
#if [ $# -eq 0 ]
#then
    PROCS=`ps auxww | \
        grep postgres: | \
        grep -v -e 'grep postgres:' -e 'postgres: stats' -e 'postgres: writer' -e 'postgres: wal writer' -e 'postgres: checkpointer' -e 'postgres: archiver' -e 'postgres: logger' -e 'postgres: autovacuum' -e 'postgres: bgworker' | \
        tee /dev/tty | \
        awk '{print $2}'`
# else
#    PROCS=`ps auxww | \
#        grep postgres: | \
#        grep -v -e 'grep postgres:' -e 'postgres: stats' -e 'postgres: writer' -e 'postgres: wal writer' -e 'postgres: checkpointer' -e 'postgres: archiver' -e 'postgres: logger' -e 'postgres: autovacuum' | \
#        grep $@ | \
#        tee /dev/tty | \
#        awk '{print $2}'`
#fi

echo $PROCS

if [ `echo "$PROCS" | wc -w` -eq 1 ]
then
    exec gdb $PGINSTROOT/bin/postgres -silent "$PROCS"
else
    exec gdb $PGINSTROOT/bin/postgres -silent
fi
