#!/usr/bin/env bash

PGDIR=$HOME/pg
PGDATA=$PGDIR/data/head
rm -r $PGDATA
initdb -N -D $PGDATA
echo "shared_buffers = 256MB" >> $PGDATA/postgresql.conf
echo "wal_level = logical" >> $PGDATA/postgresql.conf
echo "logging_collector = on" >> $PGDATA/postgresql.conf
echo "autovacuum = off" >> $PGDATA/postgresql.conf
echo "local   replication   $USER   trust" >> $PGDATA/pg_hba.conf;

if [ ! -z "$1" ]; then
	if [ "$1" != "--start" ]; then
		echo "** invalid option **"
	else
		runpg s
	fi
fi
