#!/usr/bin/env bash
PGDIR=$HOME/pg

if [ -z "$1" ]; then
	echo "** no args **";
fi

# add to PATH only if not already done
currentpgpath=`which postgres`
newpgpath=$PGDIR/install/$1/bin/postgres
if [ "$currentpgpath" == "$newpgpath" ]; then
	PATH=$PATH
else
	PATH=$PGDIR/install/$1/bin:$PATH
fi
export PATH
export PGDATA=$PGDIR/data/$1
export LD_LIBRARY_PATH=$PGDIR/install/$1/lib/:$LD_LIBRARY_PATH
