#!/usr/bin/env bash
PGDATA=/home/amit/pg/data/head
if [ -z "$1" ]; then
	echo "** no op specified **"
	return 1
else
	op=$1
	if [ "$op" != "s" -a \
		 "$op" != "x" -a \
		 "$op" != "r" -a \
		 "$op" != "start" -a \
		 "$op" != "stop" -a \
		 "$op" != "restart" ]; then
		echo "** op unrecognized **"
		return 1
	fi

	if [ "$op" == "s" ]; then
		op="start"
	elif [ "$op" == "x" ]; then
		op="stop"
	elif [ "$op" == "r" ]; then
		op="restart"
	fi
fi

pg_ctl -c -D $PGDATA $op
return 0
